Add tests and implement number of edges
algdat/blatt-2-amf0 pull request #36
Opened 2017-05-13 16:26 UTC by Areiser

2017-05-13 16:27 UTC, Areiser commented
@089 Die indegree und outdegree tests schlagen aktuell fehl. So wie ich es verstehe müsste das aber passen - da werden Kanten gezählt die es nicht gibt weil der graph nicht directed ist.

2017-05-15 14:52 UTC, 089 commented
@Areiser Wegen inDeg/outDeg: statt if (adjacencyMatrix[row][vertexIndex] ...) würde ich if (adjacencyMatrix[row][vertexIndex] > 0 ... schreiben, aber ansonsten hast du natürlich Recht.

2017-05-15 17:11 UTC, 089 requested changes
@Areiser Wegen inDeg/outDeg: statt if (adjacencyMatrix[row][vertexIndex] ...) würde ich if (adjacencyMatrix[row][vertexIndex] > 0 ... schreiben, aber ansonsten hast du natürlich Recht.

2017-05-15 18:02 UTC, Areiser commented
Sollte eigentlich keinen Unterschied machen aber ich hab es eingefügt.

2017-05-16 18:34 UTC, 089 approved these changes
:+1:

2017-05-16 18:34 UTC, merged